version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /frontend/src:/app/src
    env_file:
      - ./frontend/.dev.env
    command: 'npm run start'
